<?php

/**
 * Class DbSqlPrepareTest
 *
 * @coversDefaultClass DbSqlPrepare
 */
class DbSqlPrepareTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DbSqlPrepare $object
   */
  protected $object;

  public function setUp() {
    parent::setUp();
    $this->object = DbSqlPrepare::build('');
  }

  public function tearDown() {
    unset($this->object);
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  /**
   * @covers ::__construct
   * @covers ::build
   * @covers ::__toString
   */
  public function testBuild() {
    $this->assertEquals(
      'DbSqlPrepare',
      get_class($test =
        DbSqlPrepare
          ::build(
            'SELECT :fields FROM aTable LEFT JOIN bTable ON aTable.a = bTable.b', array(':fields' => '*')
          )
          ->comment('/* aComment */')
      )
    );
    $this->assertEquals('SELECT * FROM aTable LEFT JOIN bTable ON aTable.a = bTable.b /* aComment */', $test->__toString());
    $this->assertEquals('SELECT * FROM aTable LEFT JOIN bTable ON aTable.a = bTable.b /* bComment */', $test->comment('/* bComment */')->__toString());
    unset($test);
  }

  /**
   * covers ::__construct
   * covers ::build
   * covers ::__toString
   */
  public function NOTtestBuild() {
    $this->assertEquals(
      'DbSqlPrepare',
      get_class($test =
        DbSqlPrepare
          ::build(
            'SELECT :fields FROM :TABLE LEFT JOIN :2table ON aTable.a = bTable.b', array(':fields' => '*')
          )
//          ->tables(array(':2table' => 'bTable'))
          ->comment('/* aComment */')
      )
    );
    $this->assertEquals('/* aComment */ SELECT * FROM aTable LEFT JOIN bTable ON aTable.a = bTable.b', $test->__toString());
    $this->assertEquals('/* bComment */ SELECT * FROM aTable LEFT JOIN bTable ON aTable.a = bTable.b', $test->comment('/* bComment */')->__toString());
    unset($test);
  }

}
