<?php

class DBStaticRecordPublisher extends DBStaticRecord {

  public static function getRecord($where = '', $fieldList = array(), $for_update = false) {
    return parent::getRecord($where, $fieldList, $for_update); // TODO: Change the autogenerated stub
  }

}

/**
 * Class DBStaticRecordTest
 *
 * @coversDefaultClass DBStaticRecord
 */
class DBStaticRecordTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DBStaticRecordPublisher
   */
  protected $DBStaticRecordPublisher;

  /**
   * @var PHPUnit_Framework_MockObject_MockObject $dbStub
   */
  protected $dbStub;

  public function setUp() {
    parent::setUp();
    $this->DBStaticRecordPublisher = new DBStaticRecordPublisher();
  }

  public function tearDown() {
    parent::tearDown(); // TODO: Change the autogenerated stub
    unset($this->DBStaticRecordPublisher);
  }

  public function testNothing() {

  }

}
