<?php

/**
 * Class HelperArrayTest
 *
 * @coversDefaultClass HelperArray
 */
class HelperArrayTest extends PHPUnit_Framework_TestCase {

  public function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function tearDown() {
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  public function dataStringToArray() {
    return array(
      array(123, ',', array()), // Only string would be converted to array
      array('', ',', array()), // Empty data would be converted to empty array()
      array('123', ',', array('123')), // One element string
      array('123,234', ',', array('123', '234')), // Two element string
      array('123;234', ';', array('123', '234')), // Specified delimiter
    );
  }

  /**
   * @param string $value
   * @param string $delimiter
   * @param array  $expected
   *
   * @dataProvider dataStringToArray
   *
   * @covers ::stringToArray
   * @covers ::stringToArrayFilterEmpty
   */
  public function testStringToArray($value, $delimiter, $expected) {
    $this->assertEquals($expected, HelperArray::stringToArray($value, $delimiter));
  }


  /**
   * @covers ::makeArrayRef
   * @covers ::makeArray
   */
  public function testMakeArray() {
    // Straightforward: just array
    $test = array('test');
    $this->assertEquals(array('test'), HelperArray::makeArray($test));

    // Value with default index
    $test = 'test';
    $this->assertEquals(array(0 => 'test'), HelperArray::makeArray($test));

    // Value with non-default index
    $test = 'test';
    $this->assertEquals(array(1 => 'test'), HelperArray::makeArray($test, 1));
  }

  public function dataFilter() {
    $callback = function ($value) {
      return !empty($value);
    };

    return array(
      array(1, $callback, array()), // Not array
      array(array(), $callback, array()), // Empty array
      array(array(''), $callback, array()), // Not empty array with one empty element
      array(array('0', ''), $callback,array()), // Not empty array with both filterable elements
      array(array('test', ''), $callback, array(0 => 'test')), // Not empty array with one filterable element
    );
  }

  /**
   * @param mixed $value
   * @param callable $callback
   * @param array $expected
   *
   * @dataProvider dataFilter
   *
   * @covers ::filter
   */
  public function testFilter($value, $callback, $expected) {
    $this->assertEquals($expected, HelperArray::filter($value, $callback));
  }

  /**
   * @param mixed $value
   * @param callable $callback
   * @param array $expected

   * @dataProvider dataFilter
   *
   * @covers ::filterEmpty
   * @covers Validators::isNotEmpty
   * @covers ::filter
   */
  public function testFilterEmpty($value, $callback, $expected) {
    $this->assertEquals($expected, HelperArray::filterEmpty($value));
  }


  /**
   * @covers ::stringToArrayFilterEmpty
   * @covers ::stringToArray
   * @covers ::filterEmpty
   * @covers Validators::isNotEmpty
   * @covers ::filter
   */
  public function testStringToArrayFilterEmpty() {
    // Not string
    $this->assertEquals(array(), HelperArray::stringToArrayFilterEmpty(1));

    // Empty string
    $this->assertEquals(array(), HelperArray::stringToArrayFilterEmpty(''));
  }

  /**
   * @covers ::merge
   */
  public function testMerge() {
    // Testing ARRAY_REPLACE mode
    $array1 = array('a' => 'b');
    $array2 = array('c' => 'd', 0 => 10);
    HelperArray::merge($array1, $array2);
    $this->assertEquals($array2, $array1);

    // Testing ARRAY_MERGE mode
    // String keyed value should be replaced
    // Integer keyed value should be added and integer keys should be recalculated
    $array2 = array('c' => 'e', 0 => 20);
    HelperArray::merge($array1, $array2, HelperArray::ARRAY_MERGE);
    $this->assertEquals(array('c' => 'e', 0 => 10, 1 => 20), $array1);
  }

}
