<?php

class FleetValidatorTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Fleet $object
   */
  protected $object;

  /**
   * @var array
   */
  protected $user;

  /**
   * @var array
   */
  protected $planetrow;

  public function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
    // $this->object = new Fleet();
  }

  public function tearDown() {
    unset($this->object);
    parent::tearDown(); // TODO: Change the autogenerated stub
  }

  public function dataFleet() {
    return array(
      array(array('test'), 0, array('test')),
      array('test', 0, array(0 => 'test')),
      array('test', 1, array(1 => 'test')),
    );
  }

  /**
   * @dataProvider dataFleet
   *
   * covers ::makeArrayRef
   */
  public function testFleet($targetVector, $target_mission, $ships, $fleet_group_mr, $speed_percent, $targetUnitId = 0, $captainId, $resources) {
    // $this->object->initDefaults($this->user, $this->planetrow, $targetVector, $target_mission, $ships, $fleet_group_mr, $speed_percent, $targetUnitId, $captainId, $resources);
  }



}


//require_once('includes/includes/flt_functions.php');
//
//lng_include('fleet');
//
//$targetVector = new Vector(Vector::READ_PARAMS_FLEET, $planetrow);
//$target_mission = sys_get_param_int('target_mission', MT_NONE);
//$ships = sys_get_param_array('ships');
//$fleet_group_mr = sys_get_param_id('fleet_group');
//$speed_percent = sys_get_param_int('speed', 10);
//
//$captainId = sys_get_param_id('captain_id');
//// TODO - Missile - targeted unit ID
//
//$resources = array(
//  RES_METAL     => max(0, floor(sys_get_param_float('resource0'))),
//  RES_CRYSTAL   => max(0, floor(sys_get_param_float('resource1'))),
//  RES_DEUTERIUM => max(0, floor(sys_get_param_float('resource2'))),
//);
//
//
//// Инициализируем объекты значениями по умолчанию
$objFleet5 = new Fleet();
$objFleet5->initDefaults($user, $planetrow, $targetVector, $target_mission, $ships, $fleet_group_mr, $speed_percent, 0, $captainId, $resources);
//
//
//switch($fleet_page) {
//  case 1:
//    $objFleet5->fleetPage1();
//  break;
//
//  case 2:
//    $objFleet5->fleetPage2();
//  break;
//
//  case 3:
//    $objFleet5->fleetPage3();
//  break;
//
//  case 4:
//    require('includes/includes/flt_page4.inc');
//  break;
//
//  case 5:
//    require('includes/includes/flt_page5.inc');
//  break;
//
//  default:
//    $objFleet5->fleetPage0();
//  break;
//}
