<?php

/**
 * Class UBEFleetUnitList
 *
 * @method UBEFleetUnit offsetGet($offset)
 * @property UBEFleetUnit[] $_container
 */
class UBEFleetUnitList extends ArrayAccessV2 {

  public function __clone() {
    return parent::__clone(); // TODO: Change the autogenerated stub
  }

  // TODO - читать инфу здесь?
  public function insert_unit($unit_id, $unit_count = 0) {
    if(!isset($this[$unit_id])) {
      $this[$unit_id] = new UBEFleetUnit();
      $this[$unit_id]->id = $unit_id;
      $this[$unit_id]->count = $unit_count;
    }
  }

  public function get_unit_count() {
    $result = 0;
    foreach($this->_container as $UBEFleetUnit) {
      $result += $UBEFleetUnit->count;
    }
    return $result;
  }


  /**
   * @param $bonus_list
   */
  public function fill_unit_info($bonus_list) {
    foreach($this->_container as $UBEFleetUnit) {
      $UBEFleetUnit->fill_unit_info($bonus_list);
    }
  }

}
