<?php

/**
 * Class UBEUnitList
 *
 * @method UBEUnit offsetGet($offset)
 * @property UBEUnit[] $_container
 */
class UBEUnitList extends ArrayAccessV2 {

  public function __clone() {
    parent::__clone(); // TODO: Change the autogenerated stub
  }

  // TODO - читать инфу здесь?
  public function insert_unit($unit_id, $unit_count = 0) {
    if(!isset($this[$unit_id])) {
      $this[$unit_id] = new UBEUnit();
      $this[$unit_id]->unit_id = $unit_id;
      $this[$unit_id]->count = $unit_count;
    }
  }

  public function get_units_count() {
    $result = 0;
    foreach($this->_container as $UBEFleetUnit) {
      $result += $UBEFleetUnit->count;
    }
    return $result;
  }

  public function get_units_lost() {
    $result = 0;
    foreach($this->_container as $UBEFleetUnit) {
      $result += $UBEFleetUnit->units_lost; // Если будет сделано восстановлении более, чем начальное число - тут надо сделать сумму по модулю
    }
    return $result;
  }


  /**
   * @param $bonus_list
   */
  public function fill_unit_info($bonus_list) {
    foreach($this->_container as $UBEFleetUnit) {
      $UBEFleetUnit->fill_unit_info($bonus_list);
    }
  }


  /**
   * @param bool     $is_simulator
   *
   * @version 2016-02-25 23:42:45 41a4.68
   */
  public function prepare_for_next_round($is_simulator) {
    foreach($this->_container as $unit_id => $UBEUnit) {
      $UBEUnit->prepare_for_next_round($is_simulator);
    }
  }

  /**
   * @return int
   *
   * @version 2016-02-25 23:42:45 41a4.68
   */
  public function get_reapers() {
    $reapers = 0;

    foreach($this->_container as $unit_id => $UBEUnit) {
      // TODO: Работа по группам - группа "Уничтожители лун"
      if($UBEUnit->unit_id == SHIP_HUGE_DEATH_STAR) {
        $reapers += $UBEUnit->count;
      }
    }

    return $reapers;
  }

}
