<?php

/**
 * Class UBEUnitList
 *
 * @method void fill_unit_info(Bonus $bonus)
 * @method void prepare_for_next_round(bool $is_simulator)
 *
 * @method UBEUnit offsetGet($offset)
 * @property UBEUnit[] $_container
 *
 */
class UBEUnitList extends ArrayAccessV2 {

  /**
   * Method list that should support applying to container content
   *
   * @var string[]
   */
  protected static $_call = array(
    'fill_unit_info',
    'prepare_for_next_round',
  );

  /**
   * Contained object property list that supported by property summarizer
   *
   * @var string[]
   */
  protected static $_sum_property = array(
    'count',
    'units_lost',
  );

  public function __clone() {
    parent::__clone(); // TODO: Change the autogenerated stub
  }

  // TODO - читать инфу здесь?
  public function insert_unit($unit_id, $unit_count = 0) {
    if(!isset($this[$unit_id])) {
      $this[$unit_id] = new UBEUnit();
      $this[$unit_id]->unit_id = $unit_id;
      $this[$unit_id]->count = $unit_count;
    }
  }

  public function get_units_count() {
    return $this->getSumProperty('count');
  }

  public function get_units_lost() {
    return $this->getSumProperty('units_lost');
  }


//  /**
//   * @param Bonus $bonus
//   */
//  public function fill_unit_info(Bonus $bonus) {
//    foreach($this->_container as $UBEFleetUnit) {
//      $UBEFleetUnit->fill_unit_info($bonus);
//    }
//  }


//  /**
//   * @param bool     $is_simulator
//   *
//   * @version 2016-02-25 23:42:45 41a4.68
//   */
//  public function prepare_for_next_round($is_simulator) {
//    foreach($this->_container as $unit_id => $UBEUnit) {
//      $UBEUnit->prepare_for_next_round($is_simulator);
//    }
//  }

  /**
   * @return int
   *
   * @version 2016-02-25 23:42:45 41a4.68
   */
  public function get_reapers() {
    $reapers = 0;

    foreach($this->_container as $unit_id => $UBEUnit) {
      // TODO: Работа по группам - группа "Уничтожители лун"
      if($UBEUnit->unit_id == SHIP_HUGE_DEATH_STAR) {
        $reapers += $UBEUnit->count;
      }
    }

    return $reapers;
  }

}
