<?php
/**
 * Created by Gorlum 16.07.2017 11:43
 */

define('TEST_VALUE_SQL_DATE', '2001-01-01');
define('TEST_VALUE_INT_0', 0);
define('TEST_VALUE_INT_1', 1);
define('TEST_VALUE_INT_7', 7);

const UNIT_TEST_ID_STRING_0 = 'UNIT_TEST_ID_STRING_0';
const UNIT_TEST_ID_STRING_1 = 'UNIT_TEST_ID_STRING_1';
const UNIT_TEST_ID_STRING_2 = 'UNIT_TEST_ID_STRING_2';
const UNIT_TEST_ID_STRING_3 = 'UNIT_TEST_ID_STRING_3';
const UNIT_TEST_ID_STRING_4 = 'UNIT_TEST_ID_STRING_4';
const UNIT_TEST_ID_STRING_5 = 'UNIT_TEST_ID_STRING_5';

const UNIT_TEST_STRING = 'test';