<?php
/**
 * Created by Gorlum 27.03.2018 10:39
 */

define('UBE_COMBAT_RESULT_DRAW_END', -1);
define('UBE_COMBAT_RESULT_DRAW', 0);
define('UBE_COMBAT_RESULT_WIN', 1);
define('UBE_COMBAT_RESULT_LOSS', 2);

define('UBE_MOON_WAS', -1);
define('UBE_MOON_NONE', 0);
define('UBE_MOON_CREATE_SUCCESS', 1);
define('UBE_MOON_CREATE_FAILED', 2);
define('UBE_MOON_DESTROY_SUCCESS', 3);
define('UBE_MOON_DESTROY_FAILED', 4);
define('UBE_MOON_REAPERS_NONE', 5);
define('UBE_MOON_REAPERS_DIED', 6);
define('UBE_MOON_REAPERS_RETURNED', 7);

define('UBE_REPORT_NOT_FOUND', 'UBE_REPORT_NOT_FOUND');

define('UBE_REPORT_CYPHER', 'UBE_REPORT_CYPHER');
define('UBE_REPORT_ID', 'UBE_REPORT_ID');
define('UBE_OBJ_PREPARATOR', 'UBE_OBJ_PREPARATOR');
define('UBE_OBJ_CALCULATOR', 'UBE_OBJ_CALCULATOR');
define('UBE_TIME', 'UBE_TIME');
define('UBE_TIME_SPENT', 'UBE_TIME_SPENT');

define('UBE_OPTIONS', 'UBE_OPTIONS');
define('UBE_COMBAT_ADMIN', 'UBE_COMBAT_ADMIN');
define('UBE_DEFENDER_ACTIVE', 'UBE_DEFENDER_ACTIVE');
define('UBE_MISSION_TYPE', 'UBE_MISSION_TYPE');
define('UBE_LOADED', 'UBE_LOADED');
define('UBE_SIMULATOR', 'UBE_SIMULATOR');
define('UBE_SIMULATOR_STATIC', 'UBE_SIMULATOR_STATIC');
define('UBE_EXCHANGE', 'UBE_EXCHANGE');
define('UBE_METHOD', 'UBE_METHOD');


define('UBE_OUTCOME', 'UBE_OUTCOME');
define('UBE_COMBAT_RESULT', 'UBE_COMBAT_RESULT');
define('UBE_SFR', 'UBE_SFR');
define('UBE_DEBRIS', 'UBE_DEBRIS');
define('UBE_DEBRIS_ORIGINAL', 'UBE_DEBRIS_ORIGINAL');
define('UBE_DEBRIS_TOTAL', 'UBE_DEBRIS_TOTAL');

define('UBE_CAPTURE_RESULT', 'UBE_CAPTURE_RESULT');
define('UBE_CAPTURE_DISABLED', 0);
define('UBE_CAPTURE_NON_PLANET', 1);
define('UBE_CAPTURE_NOT_A_WIN_IN_1_ROUND', 2);
define('UBE_CAPTURE_TOO_MUCH_FLEETS', 3);
define('UBE_CAPTURE_NO_ATTACKER_USER_ID', 4);
define('UBE_CAPTURE_NO_DEFENDER_USER_ID', 5);
define('UBE_CAPTURE_CAPITAL', 6);
define('UBE_CAPTURE_TOO_LOW_POINTS', 7);
define('UBE_CAPTURE_NOT_ENOUGH_SLOTS', 8);

define('UBE_CAPTURE_SUCCESSFUL', 100);

define('UBE_PLANET', 'UBE_PLANET');
define('PLANET_ID', 'PLANET_ID');
define('PLANET_NAME', 'PLANET_NAME');
define('PLANET_SIZE', 'PLANET_SIZE');
define('PLANET_GALAXY', 'PLANET_GALAXY');
define('PLANET_SYSTEM', 'PLANET_SYSTEM');
define('PLANET_PLANET', 'PLANET_PLANET');
define('PLANET_TYPE', 'PLANET_TYPE');

define('UBE_MOON', 'UBE_MOON');
define('UBE_MOON_NAME', 'UBE_MOON_NAME');
define('UBE_MOON_CHANCE', 'UBE_MOON_CHANCE');
define('UBE_MOON_SIZE', 'UBE_MOON_SIZE');
define('UBE_MOON_REAPERS', 'UBE_MOON_REAPERS');
define('UBE_MOON_DESTROY_CHANCE', 'UBE_MOON_DESTROY_CHANCE');
define('UBE_MOON_REAPERS_DIE_CHANCE', 'UBE_MOON_REAPERS_DIE_CHANCE');


define('UBE_PLAYERS', 'UBE_PLAYERS');
define('UBE_NAME', 'UBE_NAME');
define('UBE_ATTACKER', 'UBE_ATTACKER');
define('UBE_AUTH_LEVEL', 'UBE_AUTH_LEVEL');
define('UBE_PLAYER_DATA', 'UBE_PLAYER_DATA');


define('UBE_BONUSES', 'UBE_BONUSES');
define('UBE_ATTACK', 'UBE_ATTACK');
define('UBE_SHIELD', 'UBE_SHIELD');
define('UBE_ARMOR', 'UBE_ARMOR');
define('UBE_SHIELD_REST', 'UBE_SHIELD_REST');
define('UBE_ARMOR_REST', 'UBE_ARMOR_REST');


define('UBE_FLEETS', 'UBE_FLEETS');
define('UBE_OWNER', 'UBE_OWNER');
define('UBE_FLEET_GROUP', 'UBE_FLEET_GROUP');
define('UBE_PRICE', 'UBE_PRICE');
define('UBE_AMPLIFY', 'UBE_AMPLIFY');
define('UBE_CAPACITY', 'UBE_CAPACITY');
define('UBE_TYPE', 'UBE_TYPE');
define('UBE_RESOURCES', 'UBE_RESOURCES');
define('UBE_RESOURCES_LOST', 'UBE_RESOURCES_LOST');
define('UBE_CARGO_DROPPED', 'UBE_CARGO_DROPPED');
define('UBE_RESOURCES_LOOTED', 'UBE_RESOURCES_LOOTED');
define('UBE_RESOURCES_LOST_IN_METAL', 'UBE_RESOURCES_LOST_IN_METAL');
define('UBE_FLEET_TYPE', 'UBE_FLEET_TYPE');


define('UBE_COUNT', 'UBE_COUNT');
define('UBE_UNITS_LOST', 'UBE_UNITS_LOST');
define('UBE_DEFENCE_RESTORE', 'UBE_DEFENCE_RESTORE');


define('UBE_ROUNDS', 'UBE_ROUNDS');
define('UBE_FLEET_INFO', 'UBE_FLEET_INFO');
define('UBE_UNITS_BOOM', 'UBE_UNITS_BOOM');
define('UBE_ATTACK_BASE', 'UBE_ATTACK_BASE');
define('UBE_SHIELD_BASE', 'UBE_SHIELD_BASE');
define('UBE_ARMOR_BASE', 'UBE_ARMOR_BASE');
define('UBE_ATTACKERS', 'UBE_ATTACKERS');
define('UBE_DEFENDERS', 'UBE_DEFENDERS');
define('UBE_TOTAL', 'UBE_TOTAL');
define('UBE_DAMAGE_PERCENT', 'UBE_DAMAGE_PERCENT');

define('UBE_CAPTAIN', 'UBE_CAPTAIN');
