<?php

if (!defined('INSIDE'))
{
  die('Hack attempt!');
}

$sn_data += array(
  STRUC_MINE_METAL => array(
    'name' => 'metal_mine',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 80,
      RES_CRYSTAL   => 20,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1.5,
    ),
    'metal' => 80,
    'crystal' => 20,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 1.5,
    'production' => array(
      RES_METAL     => create_function ('$level, $production_factor, $temperature', 'return  40 * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
      RES_CRYSTAL   => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_DEUTERIUM => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_ENERGY    => create_function ('$level, $production_factor, $temperature', 'return -13 * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
    ),
    'metal_perhour'     => 'return   (40 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
    'crystal_perhour'   => 'return 0;',
    'deuterium_perhour' => 'return 0;',
    'energy_perhour'    => 'return - (13 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
  ),

  STRUC_MINE_CRYSTAL => array(
    'name' => 'crystal_mine',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 48,
      RES_CRYSTAL   => 24,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1.6,
    ),
    'metal' => 48,
    'crystal' => 24,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 1.6,
    'production' => array(
      RES_METAL     => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_CRYSTAL   => create_function ('$level, $production_factor, $temperature', 'return  32 * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
      RES_DEUTERIUM => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_ENERGY    => create_function ('$level, $production_factor, $temperature', 'return -16 * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
    ),
    'metal_perhour'     => 'return 0;',
    'crystal_perhour'   => 'return   (32 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
    'deuterium_perhour' => 'return 0;',
    'energy_perhour'    => 'return - (16 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
  ),

  STRUC_MINE_DEUTERIUM => array(
    'name' => 'deuterium_sintetizer',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 225,
      RES_CRYSTAL   => 75,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1.5,
    ),
    'metal' => 225,
    'crystal' => 75,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 1.5,
    'production' => array(
      RES_METAL     => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_CRYSTAL   => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_DEUTERIUM => create_function ('$level, $production_factor, $temperature', 'return  10 * $level * pow(1.1, $level) * (0.1 * $production_factor) * (-0.002 * $temperature + 1.28);'),
      RES_ENERGY    => create_function ('$level, $production_factor, $temperature', 'return -20 * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
    ),
    'metal_perhour'     => 'return 0;',
    'crystal_perhour'   => 'return 0;',
    'deuterium_perhour' => 'return  ((10 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor) * (-0.002 * $BuildTemp + 1.28));',
    'energy_perhour'    => 'return - (20 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
  ),

  STRUC_MINE_SOLAR => array(
    'name' => 'solar_plant',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 75,
      RES_CRYSTAL   => 30,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1.5,
    ),
    'metal' => 75,
    'crystal' => 30,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 1.5,
    'production' => array(
      RES_METAL     => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_CRYSTAL   => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_DEUTERIUM => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_ENERGY    => create_function ('$level, $production_factor, $temperature', 'return  ($temperature / 5 + 15) * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
    ),
    'metal_perhour'     => 'return 0;',
    'crystal_perhour'   => 'return 0;',
    'deuterium_perhour' => 'return 0;',
    'energy_perhour'    => 'return   (($BuildTemp / 5 + 15) * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
  ),

  STRUC_MINE_FUSION => array(
    'name' => 'fusion_plant',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(3 => 5, TECH_ENERGY => 3, UNIT_PLAN_STRUC_MINE_FUSION => 1),
    'cost' => array(
      RES_METAL     => 900,
      RES_CRYSTAL   => 360,
      RES_DEUTERIUM => 180,
      RES_ENERGY    => 0,
      'factor' => 1.8,
    ),
    'metal' => 900,
    'crystal' => 360,
    'deuterium' => 180,
    'energy' => 0,
    'factor' => 1.8,
    'production' => array(
      RES_METAL     => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_CRYSTAL   => create_function ('$level, $production_factor, $temperature', 'return 0;'),
      RES_DEUTERIUM => create_function ('$level, $production_factor, $temperature', 'return -10 * $level * pow(1.1, $level) * (0.1 * $production_factor);'),
      RES_ENERGY    => create_function ('$level, $production_factor, $temperature', 'global $user;return  30 * $level * pow(1.05 + 0.01 * mrc_get_level($user, "", TECH_ENERGY), $level) * (0.1 * $production_factor);'),
    ),
    'metal_perhour'     => 'return 0;',
    'crystal_perhour'   => 'return 0;',
    'deuterium_perhour' => 'return - (10 * $BuildLevel * pow(1.1, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
    'energy_perhour'    => 'return   (30 * $BuildLevel * pow(1.05 + 0.01 * $BuildEnergyTech, $BuildLevel)) * (0.1 * $BuildLevelFactor);',
  ),

  STRUC_FACTORY_ROBOT => array(
    'name' => 'robot_factory',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 400,
      RES_CRYSTAL   => 120,
      RES_DEUTERIUM => 200,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 400,
    'crystal' => 120,
    'deuterium' => 200,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_FACTORY_NANO => array(
    'name' => 'nano_factory',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_ROBOT => 10, TECH_COMPUTER => 10),
    'cost' => array(
      RES_METAL     => 1000000,
      RES_CRYSTAL   => 500000,
      RES_DEUTERIUM => 100000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 1000000,
    'crystal' => 500000,
    'deuterium' => 100000,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_FACTORY_HANGAR => array(
    'name' => 'hangar',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_ROBOT => 2),
    'cost' => array(
      RES_METAL     => 400,
      RES_CRYSTAL   => 200,
      RES_DEUTERIUM => 100,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 400,
    'crystal' => 200,
    'deuterium' => 100,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_STORE_METAL => array(
    'name' => 'metal_store',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 2000,
      RES_CRYSTAL   => 0,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 2000,
    'crystal' => 0,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_STORE_CRYSTAL => array(
    'name' => 'crystal_store',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 2000,
      RES_CRYSTAL   => 1000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 2000,
    'crystal' => 1000,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_STORE_DEUTERIUM => array(
    'name' => 'deuterium_store',
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 2000,
      RES_CRYSTAL   => 2000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 2000,
    'crystal' => 2000,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 2,
    'type' => UNIT_STRUCTURES,
  ),

  STRUC_LABORATORY => array(
    'name' => 'laboratory',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 200,
      RES_CRYSTAL   => 400,
      RES_DEUTERIUM => 200,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 200,
    'crystal' => 400,
    'deuterium' => 200,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_TERRAFORMER => array(
    'name' => 'terraformer',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_NANO => 1, TECH_ENERGY => 12),
    'cost' => array(
      RES_METAL     => 0,
      RES_CRYSTAL   => 50000,
      RES_DEUTERIUM => 100000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 0,
    'crystal' => 50000,
    'deuterium' => 100000,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_ALLY_DEPOSIT => array(
    'name' => 'ally_deposit',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 20000,
      RES_CRYSTAL   => 40000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 20000,
    'crystal' => 40000,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_LABORATORY_NANO => array(
    'name' => 'nano',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(STRUC_LABORATORY => 10, TECH_ENERGY => 10),
    'cost' => array(
      RES_METAL     => 1500000,
      RES_CRYSTAL   => 750000,
      RES_DEUTERIUM => 150000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 1500000,
    'crystal' => 750000,
    'deuterium' => 150000,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_MOON_STATION => array(
    'name' => 'mondbasis',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'cost' => array(
      RES_METAL     => 20000,
      RES_CRYSTAL   => 40000,
      RES_DEUTERIUM => 20000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 20000,
    'crystal' => 40000,
    'deuterium' => 20000,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_MOON_PHALANX => array(
    'name' => 'phalanx',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(STRUC_MOON_STATION => 1),
    'cost' => array(
      RES_METAL     => 20000,
      RES_CRYSTAL   => 40000,
      RES_DEUTERIUM => 20000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 20000,
    'crystal' => 40000,
    'deuterium' => 20000,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_MOON_GATE => array(
    'name' => 'sprungtor',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(STRUC_MOON_STATION => 1, TECH_HYPERSPACE => 7),
    'cost' => array(
      RES_METAL     => 2000000,
      RES_CRYSTAL   => 4000000,
      RES_DEUTERIUM => 2000000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 2000000,
    'crystal' => 4000000,
    'deuterium' => 2000000,
    'energy' => 0,
    'factor' => 2,
  ),

  STRUC_SILO => array(
    'name' => 'silo',
    'type' => UNIT_STRUCTURES,
    'location' => LOC_PLANET,
    'require' => array(TECH_ENGINE_ION => 1),
    'cost' => array(
      RES_METAL     => 20000,
      RES_CRYSTAL   => 20000,
      RES_DEUTERIUM => 1000,
      RES_ENERGY    => 0,
      'factor' => 2,
    ),
    'metal' => 20000,
    'crystal' => 20000,
    'deuterium' => 1000,
    'energy' => 0,
    'factor' => 2,
    'capacity' => 12,
  ),
);

?>
