<?php

if(!defined('INSIDE'))
{
  die('Hack attempt!');
}

$sn_data += array(
  SHIP_CARGO_SMALL => array(
    'name' => 'small_ship_cargo',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 2, TECH_ENGINE_CHEMICAL => 2),
    'cost' => array(
      RES_METAL     => 2000,
      RES_CRYSTAL   => 2000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 5000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_CHEMICAL,
        'speed' => 5000,
        'consumption' => 20,
        'min_level' => 2,
      ),
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 10000,
        'consumption' => 40,
        'min_level' => 5,
      ),
    ),
    'shield' => 10,
    'attack' => 5,
    'amplify' => array(SHIP_SPY => 100, SHIP_SATTELITE_SOLAR => 250, ),
    'armor' => 400,
//    'metal' => 2000,
//    'crystal' => 2000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_CHEMICAL,
//    'speed' => 5000,
//    'consumption' => 20,
//    'tech_level' => 5,
//    'tech2' => TECH_ENGINE_ION,
//    'speed2' => 10000,
//    'consumption2' => 40,
  ),

  SHIP_CARGO_BIG => array(
    'name' => 'big_ship_cargo',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 4, TECH_ENGINE_CHEMICAL => 6),
    'cost' => array(
      RES_METAL     => 6000,
      RES_CRYSTAL   => 6000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 25000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_CHEMICAL,
        'speed' => 7500,
        'consumption' => 50,
        'min_level' => 6,
      ),
    ),
    'shield' => 25,
    'attack' => 5,
    'amplify' => array(SHIP_SPY => 100, SHIP_SATTELITE_SOLAR => 250, ),
    'armor' => 1200,
//    'metal' => 6000,
//    'crystal' => 6000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_CHEMICAL,
//    'speed' => 7500,
//    'consumption' => 50,
  ),

  SHIP_CARGO_SUPER => array(
    'name' => 'supercargo',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 8, TECH_ENGINE_ION => 5, UNIT_PLAN_SHIP_CARGO_SUPER => 1),
    'cost' => array(
      RES_METAL     => 25000,
      RES_CRYSTAL   => 15000,
      RES_DEUTERIUM => 5000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 100000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 5000,
        'consumption' => 100,
        'min_level' => 5,
      ),
    ),
    'attack' => 10,
    'armor' => 3000,
    'shield' => 50,
    'amplify' => array(SHIP_SPY => 100, SHIP_SATTELITE_SOLAR => 250, ),
//    'metal' => 25000,
//    'crystal' => 15000,
//    'deuterium' => 5000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 5000,
//    'consumption' => 100,
  ),

  SHIP_CARGO_HYPER => array(
    'name' => 'planet_cargo_hyper',
    'type' => UNIT_SHIPS,
    'location' => LOC_PLANET,
    P_STACKABLE => true,
    'require' => array(STRUC_FACTORY_HANGAR => 10, TECH_ENGINE_HYPER => 5, UNIT_PLAN_SHIP_CARGO_HYPER => 1),
    'cost' => array(
      RES_METAL     => 500000,
      RES_CRYSTAL   => 200000,
      RES_DEUTERIUM => 100000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 1000000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 2000,
        'consumption' => 1000,
        'min_level' => 5,
      ),
    ),
    'shield' => 200,
    'attack' => 50,
    'amplify' => array(SHIP_SPY => 100, SHIP_SATTELITE_SOLAR => 250, ),
    'armor' => 70000,
//    'metal' =>     500000,
//    'crystal' =>   200000,
//    'deuterium' => 100000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_HYPER,
//    'speed' => 2000,
//    'consumption' => 1000,
  ),

  SHIP_COLONIZER => array(
    'name' => 'colonizer',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 4, TECH_ENGINE_ION => 3, TECH_ASTROTECH => 2),
    'cost' => array(
      RES_METAL     => 10000,
      RES_CRYSTAL   => 20000,
      RES_DEUTERIUM => 10000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 7500,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 2500,
        'consumption' => 1000,
        'min_level' => 3,
      ),
    ),
    'shield' => 100,
    'attack' => 50,
    'amplify' => array(SHIP_SPY => 10.001, SHIP_SATTELITE_SOLAR => 21, ),
    'armor' => 3000,
//    'metal' => 10000,
//    'crystal' => 20000,
//    'deuterium' => 10000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 2500,
//    'consumption' => 1000,
  ),

  SHIP_RECYCLER => array(
    'name' => 'recycler',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 4, TECH_ENGINE_CHEMICAL => 6, TECH_SHIELD => 2),
    'cost' => array(
      RES_METAL     => 10000,
      RES_CRYSTAL   => 6000,
      RES_DEUTERIUM => 2000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 20000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_CHEMICAL,
        'speed' => 2000,
        'consumption' => 300,
        'min_level' => 6,
      ),
    ),
    'shield' => 10,
    'attack' => 1,
    'amplify' => array(SHIP_SPY => 500.05, SHIP_SATTELITE_SOLAR => 1050, ),
    'armor' => 1600,
//    'metal' => 10000,
//    'crystal' => 6000,
//    'deuterium' => 2000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_CHEMICAL,
//    'speed' => 2000,
//    'consumption' => 300,
  ),

  SHIP_SPY => array(
    'name' => 'spy_sonde',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 3, TECH_ENGINE_CHEMICAL => 3, TECH_SPY => 2),
    'cost' => array(
      RES_METAL     => 0,
      RES_CRYSTAL   => 1000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 5,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_CHEMICAL,
        'speed' => 100000000,
        'consumption' => 1,
        'min_level' => 3,
      ),
    ),
    'attack' =>  0.01,
    'armor' => 100,
    'shield' =>  0.01,
    'amplify' => array( SHIP_SPY => 1,),
//    'metal' => 0,
//    'crystal' => 1000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_CHEMICAL,
//    'speed' => 100000000,
//    'consumption' => 1,
  ),

  SHIP_SATTELITE_SOLAR => array(
    'name' => 'solar_satelit',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 1),
    'cost' => array(
      RES_METAL     => 1500,
      RES_CRYSTAL   => 2000,
      RES_DEUTERIUM => 100,
      RES_ENERGY    => 0, 
      'factor' => 1,
    ),
    'capacity' => 1,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_CHEMICAL,
        'speed' => 0,
        'consumption' => 0,
        'min_level' => 0,
      ),
    ),
    'shield' => 10,
    'attack' => 1,
    'amplify' => array(SHIP_SPY => 1, ),
    'armor' => 200,
    'comment' => 'Пулемет',
    'production' => array(
//      RES_METAL     => create_function('$level, $production_factor, $user, $planet_row', 'return 0;'),
//      RES_CRYSTAL   => create_function('$level, $production_factor, $user, $planet_row', 'return 0;'),
//      RES_DEUTERIUM => create_function('$level, $production_factor, $user, $planet_row', 'return 0;'),
      RES_ENERGY    => create_function('$level, $production_factor, $user, $planet_row', 'return ($planet_row["temp_max"] / 4 + 20) * $level * (0.1 * $production_factor);'),
    ),
//    'metal' => 1500,
//    'crystal' => 2000,
//    'deuterium' => 100,
//    'energy' => 0,
//    'factor' => 1,
//    'metal_perhour'     => 'return 0;',
//    'crystal_perhour'   => 'return 0;',
//    'deuterium_perhour' => 'return 0;',
//    'energy_perhour'    => 'return (($BuildTemp / 4) + 20) * $BuildLevel * (0.1 * $BuildLevelFactor);',
//    'tech' => TECH_ENGINE_CHEMICAL,
//    'speed' => 0,
//    'consumption' => 0,
  ),



  SHIP_SMALL_FIGHTER_LIGHT => array(
    'name' => 'light_hunter',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 1, TECH_ENGINE_CHEMICAL => 1),
    'cost' => array(
      RES_METAL     => 3000,
      RES_CRYSTAL   => 1000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 50,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_CHEMICAL,
        'speed' => 12500,
        'consumption' => 20,
        'min_level' => 1,
      ),
    ),
//    'attack' => 40,
    'attack' => 50,
    'armor' => 400,
    'shield' => 10,
    'amplify' => array(SHIP_CARGO_SMALL => 16.4, SHIP_SPY => 10.001, SHIP_SATTELITE_SOLAR => 21, ),
    P_HULL_SIZE => HULL_SIZE_SMALL,
    'comment' => 'Автопушка + ракеты, мелкие щиты',
//    'metal' => 3000,
//    'crystal' => 1000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_CHEMICAL,
//    'speed' => 12500,
//    'consumption' => 20,
  ),

  SHIP_SMALL_FIGHTER_HEAVY => array(
    'name' => 'heavy_hunter',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 3, TECH_ARMOR => 2, TECH_ENGINE_ION => 2),
    'cost' => array(
      RES_METAL     => 6000,
      RES_CRYSTAL   => 4000,
//      RES_DEUTERIUM => 200,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 100,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 10000,
        'consumption' => 75,
        'min_level' => 2,
      ),
    ),
//    'attack' => 130,
    'attack' => 150,
    'armor' => 1000,
    'shield' =>  25,
    'amplify' => array(SHIP_CARGO_SMALL => 8.2, SHIP_SPY => 3.33367, SHIP_SATTELITE_SOLAR => 7, ),
    P_HULL_SIZE => HULL_SIZE_SMALL,
    'comment' => 'ЛеЛа+Ракеты',
//    'metal' => 6000,
//    'crystal' => 4000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 10000,
//    'consumption' => 75,
  ),

  SHIP_SMALL_FIGHTER_ASSAULT => array(
    'name' => 'assault_ship',
    'type' => UNIT_SHIPS,
    'location' => LOC_PLANET,
    /*
    'require' => array(STRUC_FACTORY_HANGAR => 3, TECH_ARMOR => 2, TECH_ENGINE_ION => 2),
    'cost' => array(
      RES_METAL     => 10000,
      RES_CRYSTAL   => 5000,
      RES_DEUTERIUM => 1000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'metal' => 6000,
    'crystal' => 4000,
    'deuterium' => 0,
    'energy' => 0,
    'factor' => 1,
    'capacity' => 150,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 8000,
        'consumption' => 100,
        'min_level' => 2,
      ),
    ),
    'tech' => TECH_ENGINE_ION,
    'speed' => 10000,
    'consumption' => 75,
    'attack' => 350,
    'armor' => 1000,
    'shield' =>  50,
    P_STACKABLE => true,
    'comment' => 'ТяЛа + Ракеты х2 + чутку бомб',
    P_HULL_SIZE => HULL_SIZE_SMALL,
    */
  ),

  SHIP_MEDIUM_FRIGATE => array(
    'name' => 'crusher',
    'type' => UNIT_SHIPS,
    'location' => LOC_PLANET,
    P_STACKABLE => true,
    'require' => array(STRUC_FACTORY_HANGAR => 5, TECH_ENGINE_ION => 4, TECH_ION => 2),
    'cost' => array(
      RES_METAL     => 20000,
      RES_CRYSTAL   => 7000,
      RES_DEUTERIUM => 2000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 800,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 15000,
        'consumption' => 300,
        'min_level' => 4,
      ),
    ),
    'attack' => 400,
    'armor' => 2700,
//    'shield' =>  100,
    'shield' =>  50,
    'amplify' => array(SHIP_SMALL_FIGHTER_LIGHT => 6.15, SHIP_SPY => 1.25013, SHIP_SATTELITE_SOLAR => 2.625, UNIT_DEF_TURRET_MISSILE => 5.5, ),
    'comment' => '1 торпеда, ракеты, лазеры',
    P_HULL_SIZE => HULL_SIZE_MEDIUM,
//    'metal' => 20000,
//    'crystal' => 7000,
//    'deuterium' => 2000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 15000,
//    'consumption' => 300,
  ),
/*
  SHIP_MEDIUM_DESTROYER => array(
    'name' => 'destoyer2',
    'type' => UNIT_SHIPS,
    'location' => LOC_PLANET,
    P_STACKABLE => true,
    'require' => array(STRUC_FACTORY_HANGAR => 5, TECH_ENGINE_ION => 4, TECH_ION => 2),
    'cost' => array(
      RES_METAL     => 32000,
      RES_CRYSTAL   => 11000,
      RES_DEUTERIUM => 3000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 1000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 12500,
        'consumption' => 400,
        'min_level' => 4,
      ),
    ),
    'attack' => 600,
    'armor' => 4300,
    'shield' =>  120,
//    'amplify' => array(SHIP_SMALL_FIGHTER_LIGHT => 6.15, SHIP_SPY => 1.25013, SHIP_SATTELITE_SOLAR => 2.625, UNIT_DEF_TURRET_MISSILE => 5.5, ),
    'comment' => 'торпеды',
    P_HULL_SIZE => HULL_SIZE_MEDIUM,
//    'metal' => 20000,
//    'crystal' => 7000,
//    'deuterium' => 2000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 15000,
//    'consumption' => 300,
  ),
*/
/*
     * В современном понимании к фрегатам относятся боевые корабли среднего водоизмещения, океанской (дальней морской) зоны, обладающие универсальным ракетно-артиллерийским вооружением,
     * способные решать задачи как оборонительного (ПЛО и ПВО конвоя, корабельного соединения, самообороны), так и ударного (поддержка морских десантов, атака кораблей противника,
     * «горячая» разведка берега) характера. Достаточно чётко по массогабаритным характеристикам выделяются 2 группы фрегатов:
     *    Фрегаты I класса стандартным водоизмещением 4÷5 тыс. тонн и более, вплотную приближаясь к эсминцу по возможностями ПВО/ПЛО, но несколько уступая в ударном аспекте
     *      (за счёт более лёгких ПКР и АУ меньшего калибра). Эти корабли предназначены, в основном, для эскортирования авианосных и амфибийных групп, крупных конвоев в океанских условиях. Характерным представителем фрегата I класса является американский фрегат типа «Оливер Перри».
     *    Фрегаты II класса, имея меньшее водоизмещение (около 2000-4000 т), предназначены, в основном, для одиночной патрульной службы. Возможности ПЛО/ПВО у таких кораблей обычно ниже,
     *      но на борту имеются просторные помещения для тяжёлого вертолёта и подразделений морской пехоты, мощная артиллерия либо комплекс ПКР. Характерным представителем фрегатов 2-го
 *          ранга является французский «Лафайет».

С учётом тенденции использования при проектировании современных кораблей модульного принципа, в условиях пункта базирования, предусмотрена возможность быстрого переоборудование корабля (путём замены стандартизованных блок-модулей вооружения, судового и радиоэлектронного оборудования) под тот или иной тип боевых задач, диктуемых конкретной миссией.


Линейный корабль (сокращённо — линко́р) — класс бронированных артиллерийских военных кораблей водоизмещением от 20 до 70 тысяч тонн, длиной от 150 до 280 м, вооружённых орудиями главного калибра от 280 до 460 мм, с экипажем 1500—2800 человек. Линкоры применялись в XX веке для уничтожения кораблей противника в составе боевого соединения и артиллерийской поддержки сухопутных операций. Являлся эволюционным развитием броненосцев второй половины девятнадцатого века.


Лине́йный кре́йсер — класс артиллерийских кораблей, имеющих вооружение, близкое к линкорам, но обладающих большей скоростью хода при более лёгком бронирован
ии. Появились в начале ХХ века как развитие броненосных крейсеров. Они должны были составлять авангард главных сил флота, а в бою играть роль его быстроходного крыла.
Результаты морских сражений Первой мировой войны, а также Вашингтонское морское соглашение 1922 года прервали эволюцию линейных крейсеров.
В дальнейшем прогресс в области силовых установок привёл к слиянию линейных крейсеров и линкоров в единый класс быстроходных линейных кораблей.[1]
Тем не менее, ряд кораблей, построенных в 1930—1940-х годах, нередко именуется в военно-морской литературе линейными крейсерами в силу их промежуточного положения между «настоящими» линкорами и тяжёлыми крейсерами. Последний классический линейный крейсер «Явуз» был списан в 1954 году.[2]




     */

// Эскадренный миноносец (сокр. эсминец) — класс многоцелевых боевых быстроходных маневренных кораблей, предназначенных для борьбы с подводными лодками, летательными аппаратами (в том числе ракетами) и кораблями противника, а также для охраны и обороны соединений кораблей или конвоев судов при переходе морем. Эскадренные миноносцы могут также использоваться для разведывательной и дозорной служб, артиллерийской поддержки при высадке десанта и для постановки минных заграждений.
// Характеристики водоизмещения и основных размерений современных эсминцев УРО очень схожи с теми же характеристиками ракетных крейсеров, так что в настоящее время фактически исчезла очевидная разница между этими двумя классами кораблей.
// Кре́йсер (нидерл. kruiser, мн. ч. крейсера́ или кре́йсеры[1], от kruisen — крейсировать, плавать по определенному маршруту) — класс боевых надводных кораблей, способных выполнять задачи независимо от основного флота, среди которых может быть борьба с лёгкими силами флота и торговыми судами противника, оборона соединений боевых кораблей и конвоев судов, огневая поддержка приморских флангов сухопутных войск и обеспечение высадки морских десантов, постановка минных заграждений и другие. Со второй половины XX века тенденция к укрупнению боевых соединений для обеспечения защиты от авиации противника и специализация судов для выполнения конкретных задач привела к практическому исчезновению кораблей общего назначения, какими являются крейсера, из флотов многих стран. Только военно-морские силы США, России и Перу используют их в настоящее время.
// Ракетный крейсер — подкласс крейсеров, военный корабль крупного водоизмещения, имеющий многоцелевое назначение и вооружённый, по преимуществу, пусковыми установками управляемых ракет. Широко распространён также термин крейсер УРО (с управляемым ракетным оружием), являющийся калькой с англоязычного термина Guided Missile Cruiser, употребляемого в ВМС США. Следует отметить особенности национальной классификации: в американском флоте термином «ракетный» (CG, DG, FG) именуется корабль, оснащённый ЗРК зональной обороны, в советском/российском ВМФ приставка «ракетный» означает наличие противокорабельного ракетного комплекса (ПКРК).

  SHIP_LARGE_CRUISER => array(
    'name' => 'battle_ship',
    'type' => UNIT_SHIPS,
    'location' => LOC_PLANET,
    P_STACKABLE => true,
    'require' => array(STRUC_FACTORY_HANGAR => 7, TECH_ENGINE_HYPER => 4),
    'cost' => array(
//      RES_METAL     => 40000,
//      RES_CRYSTAL   => 25000,
      RES_METAL     => 45000,
      RES_CRYSTAL   => 15000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 1500,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 10000,
        'consumption' => 500,
        'min_level' => 4,
      ),
    ),
//    'attack' => 750,
//    'armor' =>  6500,
    'attack' => 1000,
    'armor' =>  6000,
    'shield' =>  200,
    'amplify' => array(SHIP_SPY => 0.50005, SHIP_SATTELITE_SOLAR => 1.05, UNIT_DEF_TURRET_MISSILE => 1.76, ),
    P_HULL_SIZE => HULL_SIZE_LARGE,
//    'metal' => 45000,
//    'crystal' => 15000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_HYPER,
//    'speed' => 10000,
//    'consumption' => 500,
  ),

  SHIP_LARGE_BOMBER => array(
    'name' => 'bomber_ship',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(TECH_ENGINE_ION => 6, STRUC_FACTORY_HANGAR => 8, TECH_PLASMA => 5),
    'cost' => array(
      RES_METAL     => 50000,
      RES_CRYSTAL   => 25000,
      RES_DEUTERIUM => 15000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 500,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 4000,
        'consumption' => 1000,
        'min_level' => 6,
      ),
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 5000,
        'consumption' => 1250,
        'min_level' => 8,
      ),
    ),
    'attack' => 1000,
    'armor' =>  7500,
    'shield' =>  500,
    'amplify' => array(SHIP_SPY => 0.50005, SHIP_SATTELITE_SOLAR => 1.05, UNIT_DEF_TURRET_MISSILE => 4.4, UNIT_DEF_TURRET_LASER_SMALL => 4.5, UNIT_DEF_TURRET_LASER_BIG => 9, UNIT_DEF_TURRET_ION => 8, UNIT_DEF_TURRET_PLASMA => 1.3),
    P_HULL_SIZE => HULL_SIZE_LARGE,
//    'metal' => 50000,
//    'crystal' => 25000,
//    'deuterium' => 15000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 4000,
//    'consumption' => 1000,
//    'tech_level' => 8,
//    'tech2' => TECH_ENGINE_HYPER,
//    'speed2' => 5000,
//    'consumption2' => 1250,
  ),

  SHIP_LARGE_BATTLESHIP => array(
    'name' => 'battleship',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 8, TECH_HYPERSPACE => 5, TECH_ENGINE_HYPER => 5, TECH_LASER => 12),
    'cost' => array(
//      RES_METAL     => 50000,
//      RES_CRYSTAL   => 30000,
//      RES_DEUTERIUM => 8000,
      RES_METAL     => 30000,
      RES_CRYSTAL   => 40000,
      RES_DEUTERIUM => 15000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 750,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 10000,
        'consumption' => 250,
        'min_level' => 5,
      ),
    ),
//    'attack' => 1500,
//    'armor' => 8000,
    'attack' => 700,
    'armor' => 7000,
    'shield' => 400,
    'amplify' => array(SHIP_CARGO_SUPER => 11.57143, SHIP_CARGO_SMALL => 2.92857, SHIP_CARGO_BIG => 5.25, SHIP_SMALL_FIGHTER_HEAVY => 5.85714, SHIP_MEDIUM_FRIGATE => 15.71429, SHIP_LARGE_CRUISER => 62, SHIP_SPY => 0.71436, SHIP_SATTELITE_SOLAR => 1.5,  ),
    P_HULL_SIZE => HULL_SIZE_LARGE,
///*
//    'metal' => 30000,
//    'crystal' => 40000,
//    'deuterium' => 15000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_HYPER,
//    'speed' => 10000,
//    'consumption' => 250,
//*/
  ),

  SHIP_LARGE_DESTRUCTOR => array(
    'name' => 'destructor',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 9, TECH_HYPERSPACE => 5, TECH_ENGINE_HYPER => 6),
    'cost' => array(
      RES_METAL     => 60000,
      RES_CRYSTAL   => 50000,
      RES_DEUTERIUM => 15000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 2000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 5000,
        'consumption' => 1000,
        'min_level' => 6,
      ),
    ),
//    'attack' => 2500,
//    'shield' =>  600,
    'attack' => 2000,
    'armor' => 11000,
    'shield' =>  500,
    'amplify' => array(SHIP_SPY => 0.25003, SHIP_SATTELITE_SOLAR => 0.525, SHIP_LARGE_BATTLESHIP => 7.4, UNIT_DEF_TURRET_LASER_SMALL => 1.125, ),
    P_HULL_SIZE => HULL_SIZE_LARGE,
//    'metal' => 60000,
//    'crystal' => 50000,
//    'deuterium' => 15000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_HYPER,
//    'speed' => 5000,
//    'consumption' => 1000,
  ),

  SHIP_HUGE_DEATH_STAR => array(
    'name' => 'dearth_star',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 12, TECH_HYPERSPACE => 6, TECH_ENGINE_HYPER => 7, TECH_GRAVITON => 1, UNIT_PLAN_SHIP_DEATH_STAR => 1),
    'cost' => array(
      RES_METAL     => 5000000,
      RES_CRYSTAL   => 4000000,
//      RES_DEUTERIUM => 1200000,
      RES_DEUTERIUM => 1000000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 1000000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 100,
        'consumption' => 1,
        'min_level' => 7,
      ),
    ),
    'attack' => 200000,
    'armor' =>  900000,
    'shield' =>  50000,
    'amplify' => array(SHIP_CARGO_SUPER => 2.025, SHIP_CARGO_SMALL => 0.41, SHIP_CARGO_BIG => 0.91875, SHIP_SMALL_FIGHTER_LIGHT => 0.41, SHIP_SMALL_FIGHTER_HEAVY => 0.5125, SHIP_MEDIUM_FRIGATE => 0.45375, SHIP_LARGE_CRUISER => 0.93, SHIP_COLONIZER => 3.875, SHIP_RECYCLER => 2.0125, SHIP_SPY => 0.62506, SHIP_SATTELITE_SOLAR => 1.3125, SHIP_LARGE_DESTRUCTOR => 0.2875, SHIP_LARGE_BATTLESHIP => 0.03, UNIT_DEF_TURRET_MISSILE => 0.02, UNIT_DEF_TURRET_LASER_SMALL => 0.025, UNIT_DEF_TURRET_LASER_BIG => 0.05, UNIT_DEF_TURRET_GAUSS => 0.05, UNIT_DEF_TURRET_ION => 0.25,  ),
    P_HULL_SIZE => HULL_SIZE_HUGE,
//    'tech' => TECH_ENGINE_HYPER,
//    'speed' => 100,
//    'consumption' => 1,
//    'metal' => 5000000,
//    'crystal' => 4000000,
//    'deuterium' => 1000000,
//    'energy' => 0,
//    'factor' => 1,
  ),

  SHIP_HUGE_SUPERNOVA => array(
    'name' => 'supernova',
    'type' => UNIT_SHIPS,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 15, TECH_HYPERSPACE => 7, TECH_ENGINE_HYPER => 9, TECH_GRAVITON => 1, UNIT_PLAN_SHIP_SUPERNOVA => 1),
    'cost' => array(
      RES_METAL     => 20000000,
      RES_CRYSTAL   => 15000000,
      RES_DEUTERIUM => 5000000,
//      RES_CRYSTAL   => 10000000,
//      RES_DEUTERIUM => 10000000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'capacity' => 2000000,
    'engine' => array(
      array(
        'tech' => TECH_ENGINE_HYPER,
        'speed' => 150,
        'consumption' => 250,
        'min_level' => 9,
      ),
    ),
//    'attack' => 1000000,
//    'armor' =>  3000000,
    'attack' =>  100000,
    'armor' =>  3500000,
    'shield' => 1000000,
    P_HULL_SIZE => HULL_SIZE_HUGE,
    'amplify' => array(
//SHIP_CARGO_HYPER => 1,  SHIP_CARGO_SUPER => 0.6075, SHIP_CARGO_SMALL => 0.1025, SHIP_CARGO_BIG => 0.245, SHIP_SMALL_FIGHTER_LIGHT => 0.082, SHIP_SMALL_FIGHTER_HEAVY => 0.1025, SHIP_MEDIUM_FRIGATE => 0.09075, SHIP_LARGE_CRUISER => 0.186, SHIP_COLONIZER => 0.775, SHIP_RECYCLER => 0.4025, SHIP_SPY => 0.12501, SHIP_LARGE_BOMBER => 0.2, SHIP_SATTELITE_SOLAR => 0.2625, SHIP_LARGE_DESTRUCTOR => 0.0575, SHIP_DEATH_STAR => 1, SHIP_LARGE_BATTLESHIP => 0.111, SHIP_SUPERNOVA => 1, UNIT_DEF_TURRET_MISSILE => 0.004, UNIT_DEF_TURRET_LASER_SMALL => 0.005, UNIT_DEF_TURRET_LASER_BIG => 0.01, UNIT_DEF_TURRET_GAUSS => 0.01, UNIT_DEF_TURRET_ION => 0.05, UNIT_DEF_TURRET_PLASMA => 1, UNIT_DEF_SHIELD_SMALL => 1, UNIT_DEF_SHIELD_BIG => 1, UNIT_DEF_SHIELD_PLANET => 1

SHIP_CARGO_SMALL => 1, SHIP_CARGO_BIG => 3, SHIP_CARGO_SUPER => 6, SHIP_CARGO_HYPER => 10,
SHIP_RECYCLER => 5, SHIP_SPY => 2, SHIP_SATTELITE_SOLAR => 3, SHIP_COLONIZER => 8, 

SHIP_SMALL_FIGHTER_LIGHT => 0.861, SHIP_SMALL_FIGHTER_HEAVY => 0.871,
SHIP_MEDIUM_FRIGATE => 5, SHIP_LARGE_BOMBER => 5,
SHIP_LARGE_CRUISER => 1.86, SHIP_LARGE_BATTLESHIP => 1.11,
SHIP_LARGE_DESTRUCTOR => 0.575, SHIP_DEATH_STAR => 10, SHIP_SUPERNOVA => 10,

 UNIT_DEF_TURRET_MISSILE => 0.04, UNIT_DEF_TURRET_LASER_SMALL => 0.05, UNIT_DEF_TURRET_LASER_BIG => 0.1, UNIT_DEF_TURRET_GAUSS => 0.1, UNIT_DEF_TURRET_ION => 0.5, UNIT_DEF_TURRET_PLASMA => 1, UNIT_DEF_SHIELD_SMALL => 1, UNIT_DEF_SHIELD_BIG => 1, UNIT_DEF_SHIELD_PLANET => 1
      // SHIP_CARGO_SUPER => 0.6075, SHIP_CARGO_SMALL => 0.1025, SHIP_CARGO_BIG => 0.245, SHIP_MEDIUM_FRIGATE => 0.09075, SHIP_COLONIZER => 0.775, SHIP_RECYCLER => 0.4025, SHIP_SPY => 0.12501, SHIP_SATTELITE_SOLAR => 0.2625, UNIT_DEF_TURRET_MISSILE => 0.004, UNIT_DEF_TURRET_LASER_SMALL => 0.005, UNIT_DEF_TURRET_LASER_BIG => 0.01, UNIT_DEF_TURRET_GAUSS => 0.01, UNIT_DEF_TURRET_ION => 0.05,
//      SHIP_SMALL_FIGHTER_LIGHT => 0.1,
//      SHIP_SMALL_FIGHTER_HEAVY => 0.1,
//      SHIP_SMALL_FIGHTER_LIGHT => 0.861,
//      SHIP_SMALL_FIGHTER_HEAVY => 0.871,
//      SHIP_LARGE_CRUISER => 2,
//      SHIP_LARGE_BOMBER => 2,
//      SHIP_LARGE_BATTLESHIP => 1.5,
//      SHIP_LARGE_DESTRUCTOR => 10,
//
//      SHIP_DEATH_STAR => 10,
//      SHIP_SUPERNOVA => 10,
    ),
//    'metal' => 20000000,
//    'crystal' => 15000000,
//    'deuterium' => 5000000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_HYPER,
//    'speed' => 150,
//    'consumption' => 250,
  ),



  UNIT_DEF_TURRET_MISSILE => array(
    'name' => 'misil_launcher',
    'type' => UNIT_DEFENCE,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 1),
    'cost' => array(
      RES_METAL     => 2000,
      RES_CRYSTAL   => 0,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'attack' => 50,
    'attack' => 80,
    'armor' => 200,
    'shield' => 20,
    'amplify' => array(SHIP_SPY => 6.25063, ),
//    'metal' => 2000,
//    'crystal' => 0,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
  ),

  UNIT_DEF_TURRET_LASER_SMALL => array(
    'name' => 'small_laser',
    'type' => UNIT_DEFENCE,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(TECH_ENERGY => 1, STRUC_FACTORY_HANGAR => 2, TECH_LASER => 3),
    'cost' => array(
      RES_METAL     => 1500,
//      RES_CRYSTAL   => 750,
      RES_CRYSTAL   => 500,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'shield' => 25,
    'attack' => 100,
    'amplify' => array(SHIP_SPY => 5.0005, ),
    'armor' => 200,
//    'metal' => 1500,
//    'crystal' => 500,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
  ),

  UNIT_DEF_TURRET_LASER_BIG => array(
    'name' => 'big_laser',
    'type' => UNIT_DEFENCE,
    'location' => LOC_PLANET,
    'require' => array(TECH_ENERGY => 3, STRUC_FACTORY_HANGAR => 4, TECH_LASER => 6),
    'cost' => array(
      RES_METAL     => 6000,
      RES_CRYSTAL   => 2000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 6000,
//    'crystal' => 2000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
    'shield' => 100,
    'attack' => 250,
    'amplify' => array(SHIP_SPY => 2.0002, ),
    'armor' => 800,
    P_STACKABLE => true,
  ),

  UNIT_DEF_TURRET_GAUSS => array(
    'name' => 'gauss_canyon',
    'type' => UNIT_DEFENCE,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 6, TECH_ENERGY => 6, TECH_WEAPON => 3, TECH_SHIELD => 1),
    'cost' => array(
      RES_METAL     => 20000,
      RES_CRYSTAL   => 15000,
      RES_DEUTERIUM => 2000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 20000,
//    'crystal' => 15000,
//    'deuterium' => 2000,
//    'energy' => 0,
//    'factor' => 1,
    'attack' => 1100,
    'armor' => 3500,
    'shield' => 200,
    'amplify' => array(SHIP_SPY => 0.45459, ),
    P_STACKABLE => true,
  ),

  UNIT_DEF_TURRET_ION => array(
    'name' => 'ionic_canyon',
    'type' => UNIT_DEFENCE,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 4, TECH_ION => 4),
    'cost' => array(
      RES_METAL     => 2000,
      RES_CRYSTAL   => 6000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 2000,
//    'crystal' => 6000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
    'shield' => 500,
    'attack' => 150,
    'amplify' => array(SHIP_SPY => 3.33367, ),
    'armor' => 800,
    P_STACKABLE => true,
  ),

  UNIT_DEF_TURRET_PLASMA => array(
    'name' => 'buster_canyon',
    'type' => UNIT_DEFENCE,
    'location' => LOC_PLANET,
    'require' => array(STRUC_FACTORY_HANGAR => 8, TECH_PLASMA => 7),
    'cost' => array(
      RES_METAL     => 50000,
      RES_CRYSTAL   => 50000,
      RES_DEUTERIUM => 30000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 50000,
//    'crystal' => 50000,
//    'deuterium' => 30000,
//    'energy' => 0,
//    'factor' => 1,
    'shield' => 300,
    'attack' => 3000,
    'amplify' => array(SHIP_SPY => 0.16668, ),
    'armor' => 10000,
    P_STACKABLE => true,
  ),

  UNIT_DEF_SHIELD_SMALL => array(
    'name' => 'small_protection_shield',
    'type' => UNIT_DEFENCE,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(TECH_SHIELD => 2, STRUC_FACTORY_HANGAR => 1),
    'cost' => array(
      RES_METAL     => 10000,
      RES_CRYSTAL   => 10000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 10000,
//    'crystal' => 10000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
    'shield' => 2000,
    'attack' => 1,
    'amplify' => array(SHIP_SPY => 500.05, ),
    'armor' => 2000,
    P_STACKABLE => true,
    'max' => 1,
  ),

  UNIT_DEF_SHIELD_BIG => array(
    'name' => 'big_protection_shield',
    'type' => UNIT_DEFENCE,
    'location' => LOC_PLANET,
    'require' => array(TECH_SHIELD => 6, STRUC_FACTORY_HANGAR => 6),
    'cost' => array(
      RES_METAL     => 50000,
      RES_CRYSTAL   => 50000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 50000,
//    'crystal' => 50000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
    'shield' => 2000,
    'attack' => 1,
    'amplify' => array(SHIP_SPY => 500.05, ),
    'armor' => 10000,
    'max' => 1,
  ),

  UNIT_DEF_SHIELD_PLANET => array(
    'name'      => 'planet_protector',
    'type' => UNIT_DEFENCE,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require'   => array(UNIT_PLAN_DEF_SHIELD_PLANET => 1),
    'cost' => array(
      RES_METAL     => 10000000,
      RES_CRYSTAL   => 5000000,
      RES_DEUTERIUM => 2500000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal'     => 10000000,
//    'crystal'   => 5000000,
//    'deuterium' => 2500000,
//    'energy'    => 0,
//    'factor'    => 1,
    'shield'    => 1000000,
//    'attack'    => 250000,
    'attack'    => 1000000,
    'amplify'   => array(SHIP_CARGO_SUPER => 0.2025, SHIP_CARGO_SMALL => 0.041, SHIP_CARGO_BIG => 0.098, SHIP_SMALL_FIGHTER_LIGHT => 0.03075, SHIP_SMALL_FIGHTER_HEAVY => 0.0615, SHIP_MEDIUM_FRIGATE => 0.055, SHIP_LARGE_CRUISER => 0.124, SHIP_COLONIZER => 0.31, SHIP_RECYCLER => 0.161, SHIP_SPY => 0.05001, SHIP_LARGE_BOMBER => 0.08, SHIP_SATTELITE_SOLAR => 0.105, SHIP_LARGE_DESTRUCTOR => 0.023, SHIP_LARGE_BATTLESHIP => 0.037, ),
    'armor'     => 1500000,
    'max' => 1,
  ),



  UNIT_DEF_MISSILE_INTERCEPTOR => array(
    'name' => 'interceptor_misil',
    'type' => UNIT_DEFENCE,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_SILO => 2),
    'cost' => array(
      RES_METAL     => 8000,
      RES_CRYSTAL   => 2000,
      RES_DEUTERIUM => 0,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
//    'metal' => 8000,
//    'crystal' => 2000,
//    'deuterium' => 0,
//    'energy' => 0,
//    'factor' => 1,
    'shield' => 1,
    'attack' => 1,
    'armor' => 1000,
    'size' => 1,
  ),

  UNIT_DEF_MISSILE_INTERPLANET => array(
    'name' => 'interplanetary_misil',
    'type' => UNIT_DEFENCE,
    P_STACKABLE => true,
    'location' => LOC_PLANET,
    'require' => array(STRUC_SILO => 4, TECH_ENGINE_ION => 2),
    'cost' => array(
      RES_METAL     => 12500,
      RES_CRYSTAL   => 2500,
      RES_DEUTERIUM => 10000,
      RES_ENERGY    => 0,
      'factor' => 1,
    ),
    'shield' => 1,
    'attack' => 120000,
    'armor' => 1500,
    'size' => 3,
    'capacity' => 10,

    'engine' => array(
      array(
        'tech' => TECH_ENGINE_ION,
        'speed' => 10000000,
        'consumption' => 10,
        'min_level' => 2,
      ),
    ),
//    'metal' => 12500,
//    'crystal' => 2500,
//    'deuterium' => 10000,
//    'energy' => 0,
//    'factor' => 1,
//    'tech' => TECH_ENGINE_ION,
//    'speed' => 10000000,
//    'consumption' => 10,
  ),
);
